const fs = require('fs');

//creating new folder
fs.mkdirSync("demofolder");

//create a new file in the named folder
fs.openSync("demofolder/demofile.txt",'w');
 
//to write content inside the file 
fs.writeFileSync("demofolder/demofile.txt", "this the text generated by javascript")

//this function true or false if the folder is present or not
if(fs.existsSync("demofolder"))
{
    console.log("yes the folder exist")
}